version: 2
updates:
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "yourusername"  # Sostituisci con il tuo username GitHub
    commit-message:
      prefix: "deps"
      include: "scope"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "yourusername"  # Sostituisci con il tuo username GitHub
    commit-message:
      prefix: "ci"
      include: "scope" 