name: Deploy documentation

on:
  push:
    branches:
      - master  # o main, a seconda del nome del tuo branch principale
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-deploy.yml'
  workflow_dispatch:  # Consente di attivare il workflow manualmente dall'interfaccia GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessario per ottenere la storia completa per mkdocs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          # Installa eventuali plugin o estensioni aggiuntive
          # pip install mkdocs-awesome-pages-plugin

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Fix documentation links
        run: |
          # Sostituisci tutti i link .html con .md nei file di documentazione
          find docs -type f -name "*.md" -exec sed -i 's/\.html)/\.md)/g' {} \;

      - name: Build and deploy documentation
        run: |
          mkdocs build
          mkdocs gh-deploy --force --no-history
